[project]
name = "binwalk"
description = "Firmware analysis tool"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Craig Heffner"}]
requires-python = ">=3"
version = "2.3.3"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
